### ISSUE TITLE
Connections between SCA (Sonarqube Scanner), Sonarqube and SSC

### ISSUE THREAD

**Issue by giper45** [fortify-ps/fortify-integration-sonarqube#1]
Hello, I am analyzing the tcp packets (in order to set rule firewall), and the following thing happens: 

- All communications are between SCA machine (where sonarqube scanner is performed) and SSC server or Sonarqube server (also the upload) 
- No communications between Sonarqube server and SSC server

Is it correct or am I wrong analysis? How  is it possible this if the plugin is loaded on Sonarqube server ? 
Thanks in advance!

**Comment by rsenden** [comment]
The plugin only operates if it has been configured correctly with SSC URL, credentials, and application version, otherwise execution is skipped.

In the older versions, the plugin would connect to SSC from the scanner side only. With the new version (for which an alpha release is now available), the plugin connects to SSC from both scanner side and compute engine side (i.e. from SonarQube server).
